name: Docker
on:
  push:
    tags:
      - '*.*.*'
jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Docker tag
        id: docker_tag
        run: |
          DOCKER_IMAGE=akosiaris/miniflux
          DOCKER_VERSION=dev
          if [ "${{ github.event_name }}" = "schedule" ]; then
            DOCKER_VERSION=nightly
            TAGS="${DOCKER_IMAGE}:${DOCKER_VERSION}"
            elif [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_VERSION=${GITHUB_REF#refs/tags/}
            TAGS="${DOCKER_IMAGE}:${DOCKER_VERSION}"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packaging/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_tag.outputs.tags }}
